language: java
jdk:
 # - openjdk7
 # - oraclejdk7
  - oraclejdk8
sudo: false # faster builds
services:
  - postgresql
before_script:
  - psql -c "create user clnnode with password 'hotCave13';" -U postgres
  - psql -U postgres -a -f ./src/main/resources/structure.sql
script: mvn cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)